Repository jinkwon9301/Oh-my-tangerine, pull requests merged in 2022-01, with the labels that each got.

#2 풀 리퀘스트 템플릿 추가
  .github/pull_request_template.md
Labels: Merge 요청

#1 상품 등록 마크업 및 css, 기능구현
  .DS_Store
  src/Components/Chat.jsx
  src/Components/Header/HeaderWithMoreBtn.jsx
  src/Components/InputChat.jsx
  src/Components/UploadContent.jsx
  src/Routes.js
  src/pages/Post/Post.jsx
  src/pages/Post/Upload.jsx
  src/pages/Resistration/Resistration.jsx
  src/styles/GlobalStyle.js
  yarn.lock
Labels: 리뷰 요청

#4 팔로워스 마크업, css, 팔로우, 기능구현
  public/image/Ellipse 1 (1).png
  public/image/Ellipse 1 (2).png
  public/image/Ellipse 1 (3).png
  public/image/Ellipse 1 (4).png
  public/image/Ellipse 1 (5).png
  public/image/Ellipse 1 (6).png
  public/image/Ellipse 1.png
  src/Components/Follower.jsx
  src/Components/NavBottom.jsx
  src/Routes.js
  src/pages/Followers/Followers.jsx
Labels: 리뷰 요청

#3 refactory: React에 적합하게 Component화
  public/image/icon/icon-edit-fill.svg
  src/Components/Feed.jsx
  src/Components/NavBottom.jsx
  src/Components/Profile/HeadRightButton.jsx
  src/Components/Profile/UserBtnCircle.jsx
  src/Components/Profile/UserButton.jsx
  src/Components/UploadContent.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/NavBottom.jsx
  src/pages/Profile/Header.jsx
  src/pages/Profile/Header.module.css
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileInfo.jsx
  src/pages/Profile/Setting.jsx
  src/pages/Profile/SettingProfileEdit.jsx
  src/pages/Profile/SettingProfileEdit.module.css
  src/pages/Upload/Upload.jsx
Labels: 리뷰 요청

#5 Chat/list UI 페이지 생성 및 마이너 컴포넌트 수정
  src/Components/Follower.jsx
  src/Components/Header/HeaderWithClickBtn.jsx
  src/Components/Header/HeaderWithMoreBtn.jsx
  src/Components/Profile/Header.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatTemplate.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Setting.jsx
  src/styles/theme.js
Labels: 리뷰 요청

#6 feat, refactory: 채팅방 구현, 라우터로 chat/:id 연결 및 기타 마이너 이슈 수정
  src/Components/Chat/ChatMsgMe.jsx
  src/Components/Chat/ChatMsgOther.jsx
  src/Components/Header/HeaderWithClickBtn.jsx
  src/Components/Header/HeaderWithMoreBtn.jsx
  src/Components/UploadContent.jsx
  src/Routes.js
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatMsg.jsx
  src/pages/Chat/ChatRoom.jsx
Labels: 리뷰 요청

#7 Fix css/post,upload,resistraion
  src/Components/UploadContent.jsx
  src/pages/Home/Home.jsx
  src/pages/Post/Post.jsx
  src/pages/Resistration/Resistration.jsx
  src/pages/Upload/Upload.jsx
Labels: 리뷰 요청

#9 fix feature : goBack
  src/Components/Header/HeaderWithClickBtn.jsx
  src/Components/Header/HeaderWithMoreBtn.jsx
  src/pages/Profile/Profile.jsx
Labels: 리뷰 요청

#11 feat: 프로필 페이지 내 판매 중인 상품, 피드 구현
  public/image/product/product-img-1.png
  public/image/product/product-img-2.jpg
  public/image/product/product-img-3.jpg
  src/Components/Profile/NowSales.jsx
  src/Components/Profile/ProfileInfo.jsx
  src/Components/Profile/SalesProductInfo.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileInfo.jsx
  src/pages/Profile/ProfileInfo.module.css
Labels: 리뷰 요청

#8 README.md 수정
  README.md
Labels: Merge 요청

#13 검색시 공백 부분이 나타나지 않는 오류 수정
  src/Components/Search/SearchUserInfo.jsx
  src/pages/Search/Search.jsx
Labels: 리뷰 요청

#15 로그인 페이지 UI 제작
  .gitignore
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
  src/pages/Login/LoginButton.jsx
  src/pages/Login/LoginEmail.jsx
  src/pages/Login/LoginEmail.module.css
  src/pages/Login/LoginMember.jsx
  src/pages/Login/LoginMembership.jsx
  src/pages/Login/LoginMembership.module.css
  src/pages/Login/LoginProfile.jsx
  src/pages/Login/LoginProfile.module.css
Labels: 리뷰 요청

#16 로그인 페이지 머지 후 발생한 이미지 ui 사이즈 문제 수정
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
Labels: 리뷰 요청

#17 feat: 상품 등록 페이지 구현
  src/pages/Modification/Modification.jsx
  src/pages/Modification/ProductContent.jsx
Labels: Merge 요청, 리뷰 요청

#18 fix/routes
  src/Routes.js
Labels: 리뷰 요청

#22 에러나는 라우터 경로 수정
  src/Routes.js
Labels: Merge 요청

#21 search api 연결
  src/Components/Search/SearchUserInfo.jsx
  src/pages/Search/Search.jsx
  yarn.lock
Labels: 리뷰 요청

#24 profile API 적용
  src/Components/Follower.jsx
  src/Components/Profile/ProfileInfo.jsx
  src/Routes.js
  src/pages/Followers/Followings.jsx
Labels: 리뷰 요청

#26 profile api 연동 추가
  src/Components/Profile/Header.jsx
  src/Components/Profile/ProfileInfo.jsx
  src/Routes.js
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Followings.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Registration/Registration.jsx
Labels: 리뷰 요청

#25 feat: 회원가입 API 구현, 회원가입 페이지 styled component 적용
  src/pages/Chat/ChatTemplate.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
  src/pages/Login/LoginEmail.jsx
  src/pages/Login/LoginEmail.module.css
  src/pages/Login/LoginMembership.jsx
  src/pages/Login/LoginMembership.module.css
  src/pages/Login/LoginProfile.jsx
  src/pages/Login/LoginProfile.module.css
Labels: 리뷰 요청

#27 feat: Home Feed API 응답값으로 구현, 마이너 이슈 수정
  src/Components/Feed.jsx
  src/Components/UserInfo.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/LoginMembership.jsx
  src/pages/Search/Search.jsx
Labels: Merge 요청, 리뷰 요청

#28 프로필 수정 api 연동
  src/Components/Follower.jsx
  src/Components/Profile/Header.jsx
  src/Components/Profile/ProfileInfo.jsx
  src/Components/Profile/UserButton.jsx
  src/Store.js
  src/pages/Follow/Followers.jsx
  src/pages/Login/LoginEmail.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Setting.jsx
  src/pages/Profile/SettingProfileEdit.jsx
Labels: 리뷰 요청

#30 프로필 api 연동
  src/Components/Header/HeaderWithClickBtn.jsx
  src/Components/Header/HeaderWithMoreBtn.jsx
  src/Components/Profile/NowSales.jsx
  src/Components/Profile/ProfileInfo.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Setting.jsx
  src/pages/Profile/SettingProfileEdit.jsx
  src/pages/Registration/Registration.jsx
Labels: 도움 요청, 리뷰 요청

#31 상품등록 api 연동
  src/Components/Follower.jsx
  src/pages/Follow/Followers.jsx
  src/pages/Follow/Followings.jsx
  src/pages/Registration/Registration.jsx
Labels: 리뷰 요청

#32 feat: 게시글 내 복수의 이미지 슬라이드로 보이기
  src/Components/Feed.jsx
Labels: Merge 요청, 리뷰 요청

#33 Upload/api
  src/Components/UploadContent.jsx
  src/pages/Upload/Upload.jsx
Labels: 리뷰 요청

#34 Heart/api
  src/Components/Feed.jsx
  src/Components/Header/HeaderWithMoreBtn.jsx
  src/Components/Profile/NowSales.jsx
  src/Components/UserInfo.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
Labels: 리뷰 요청

#35 댓글 삭제 기능 구현
  src/Components/Feed.jsx
  src/Components/ModalOption.jsx
  src/Components/Post/Comment.jsx
  src/pages/Post/Post.jsx
Labels: 도움 요청, 리뷰 요청

#37 Profile/api
  src/Components/Header/HeaderWithMoreBtn.jsx
  src/Components/ModalOption.jsx
  src/Components/NavBottom.jsx
  src/Components/Post/Comment.jsx
  src/Components/Post/InputComment.jsx
  src/Components/Profile/NowSales.jsx
  src/Components/UserInfo.jsx
  src/pages/Post/Post.jsx
Labels: 리뷰 요청

#41 Post, Comment 관련 페이지 수정
  src/Components/Feed.jsx
  src/Components/Post/Comment.jsx
  src/pages/Home/Home.jsx
  src/pages/Post/Post.jsx
  src/pages/Profile/Profile.jsx
Labels: Merge 요청
